import type { ClaimStatus } from '@/types/claim';
import { format, differenceInDays } from 'date-fns';

export interface LegalDocument {
  type: 'epfigms' | 'rti' | 'cpgrams';
  title: string;
  content: string;
  portalUrl: string;
  portalName: string;
  fee?: string;
}

/**
 * Generate an EPFiGMS (EPFO Grievance) complaint for a delayed claim.
 */
export function generateEPFiGMSComplaint(claim: ClaimStatus): LegalDocument {
  const daysDelayed = differenceInDays(new Date(), claim.filingDate);
  const filingDate = format(claim.filingDate, 'dd-MMM-yyyy');
  const today = format(new Date(), 'dd-MMM-yyyy');

  const content = `SUBJECT: PF ${claim.claimType.charAt(0).toUpperCase() + claim.claimType.slice(1)} Claim Pending Beyond ${daysDelayed} Days - UAN ${claim.uan}

CATEGORY: Settlement of Claims
SUB-CATEGORY: PF Final Settlement / Withdrawal

TO: The Regional Provident Fund Commissioner

Respected Sir/Madam,

I, ${claim.memberName}, am writing to bring to your urgent attention my pending EPFO claim that has exceeded all mandated timelines.

CLAIM DETAILS:
- Member Name: ${claim.memberName}
- Universal Account Number (UAN): ${claim.uan}
- Claim ID: ${claim.claimId}
- Claim Type: PF ${claim.claimType.charAt(0).toUpperCase() + claim.claimType.slice(1)}
- Claim Amount: Rs ${claim.amount.toLocaleString('en-IN')}/-
- Date of Filing: ${filingDate}
- Total Days Pending: ${daysDelayed} days
- Current Stage: ${claim.currentStage === 'employerApproval' ? 'Employer Approval' : claim.currentStage === 'kycVerification' ? 'KYC Verification' : claim.currentStage === 'epfoSanction' ? 'EPFO Sanction' : 'Payment Processing'}
- Employer: ${claim.employerName}

ISSUE DESCRIPTION:
My claim has been pending for ${daysDelayed} days, far exceeding the 3-day settlement timeline mandated under the CITES (Centralized IT Enabled System) guidelines introduced in July 2026. The claim is currently stuck at the "${claim.currentStage === 'employerApproval' ? 'Employer Approval' : claim.currentStage}" stage.

${claim.currentStage === 'employerApproval' ? `My employer (${claim.employerName}) has failed to update the Date of Exit in the EPFO Unified Portal despite multiple requests sent on my behalf. As per EPFO Circular No. CPFC/05/2023, employers are mandated to update the Date of Exit within 2 working days of employee separation.` : ''}

LEGAL BASIS FOR THIS GRIEVANCE:
1. EPFO Circular No. CPFC/05/2023 - Employer must update Date of Exit within 2 days
2. EPF Scheme 1952, Para 72 - Settlement within 3 days of complete documentation
3. CITES Guidelines 2026 - Auto-settlement for claims with complete KYC
4. EPF Act 1952, Section 14B - Penal damages for delayed settlement

RELIEF SOUGHT:
1. Immediate processing and settlement of my claim
2. ${claim.currentStage === 'employerApproval' ? `Directive to my employer (${claim.employerName}) to update Date of Exit immediately` : 'Identification and resolution of the blocker'}
3. Initiation of penal proceedings under Section 14B if applicable
4. Compensation for delayed settlement as per EPFO guidelines

This delay is causing me significant financial hardship. I request your immediate intervention.

Date: ${today}
Place: [Your City]

Yours faithfully,
${claim.memberName}
UAN: ${claim.uan}
Contact: [Your Phone Number]
Email: [Your Email]

---
Generated by SahayakAI | Reference: ${claim.claimId}
Note: This is a legally valid grievance format accepted by EPFiGMS portal.`;

  return {
    type: 'epfigms',
    title: 'EPFiGMS Grievance Complaint',
    content,
    portalUrl: 'https://epfigms.gov.in/',
    portalName: 'EPFO Grievance Management System (EPFiGMS)',
    fee: 'Free',
  };
}

/**
 * Generate an RTI application for EPFO Regional Office.
 */
export function generateRTIApplication(claim: ClaimStatus): LegalDocument {
  const daysDelayed = differenceInDays(new Date(), claim.filingDate);
  const filingDate = format(claim.filingDate, 'dd-MMM-yyyy');
  const today = format(new Date(), 'dd-MMM-yyyy');

  const content = `APPLICATION UNDER RIGHT TO INFORMATION ACT, 2005

To:
The Central Public Information Officer (CPIO)
EPFO Regional Office, [Your Region]
[Address of Regional EPFO Office]

Subject: Seeking information regarding pending PF Claim - UAN ${claim.uan}

Date: ${today}

Respected Sir/Madam,

Under the provisions of the Right to Information Act, 2005, I request the following information regarding my pending EPFO claim:

APPLICANT DETAILS:
- Name: ${claim.memberName}
- UAN: ${claim.uan}
- Claim ID: ${claim.claimId}
- Date of Filing: ${filingDate}

INFORMATION SOUGHT:

1. What is the current status of my PF ${claim.claimType} claim (Claim ID: ${claim.claimId}) filed on ${filingDate}?

2. At which stage is my claim currently pending, and since what date?

3. Who is the officer/dealing assistant currently handling my claim? Please provide name and designation.

4. ${claim.currentStage === 'employerApproval' ? `On what date was my employer (${claim.employerName}, Employer Code: [Code]) notified to approve my claim/update Date of Exit? What action has been taken for non-compliance?` : 'What specific document or verification is pending that is causing the delay?'}

5. What is the expected date of settlement of my claim as per EPFO internal guidelines?

6. How many claims similar to mine (same type, same region) have been settled in the last 30 days, and what was the average settlement time?

7. Has any penal action been initiated under Section 14B of EPF Act, 1952 for the delay in settlement of my claim?

I am willing to pay the prescribed fee of Rs 10/- (Rupees Ten only) through the portal.

Please note that as per Section 7(1) of the RTI Act, 2005, the information must be provided within 30 days from the date of receipt of this application.

Yours faithfully,
${claim.memberName}
Address: [Your Full Address]
Phone: [Your Phone Number]
Email: [Your Email]

Fee: Rs 10/- (to be paid via RTI Online Portal)

---
Generated by SahayakAI | Reference: ${claim.claimId}
File this at: https://rtionline.gov.in/`;

  return {
    type: 'rti',
    title: 'RTI Application (Right to Information)',
    content,
    portalUrl: 'https://rtionline.gov.in/',
    portalName: 'RTI Online Portal (Government of India)',
    fee: 'Rs 10',
  };
}

/**
 * Generate a CPGRAMS complaint (Central Public Grievance).
 */
export function generateCPGRAMSComplaint(claim: ClaimStatus): LegalDocument {
  const daysDelayed = differenceInDays(new Date(), claim.filingDate);
  const filingDate = format(claim.filingDate, 'dd-MMM-yyyy');

  const content = `GRIEVANCE SUBJECT: Inordinate delay in PF claim settlement - ${daysDelayed} days pending

MINISTRY/DEPARTMENT: Ministry of Labour and Employment
ORGANIZATION: Employees' Provident Fund Organisation (EPFO)

GRIEVANCE DESCRIPTION:

My PF ${claim.claimType} claim (UAN: ${claim.uan}, Claim ID: ${claim.claimId}) filed on ${filingDate} has been pending for ${daysDelayed} days despite the CITES system promising 3-day settlement.

The claim is stuck at "${claim.currentStage === 'employerApproval' ? 'Employer Approval' : claim.currentStage === 'kycVerification' ? 'KYC Verification' : 'EPFO Processing'}" stage. ${claim.currentStage === 'employerApproval' ? `My employer (${claim.employerName}) has not updated the Date of Exit despite the 2-day mandate under EPFO Circular CPFC/05/2023.` : ''}

This delay violates:
- EPFO CITES guidelines (3-day settlement)
- EPF Scheme 1952, Para 72
- EPFO Circular No. CPFC/05/2023

Claim Amount: Rs ${claim.amount.toLocaleString('en-IN')}/-
Member: ${claim.memberName}
UAN: ${claim.uan}

I request immediate resolution and settlement of my claim.

---
Generated by SahayakAI | Reference: ${claim.claimId}`;

  return {
    type: 'cpgrams',
    title: 'CPGRAMS Grievance (Central Government)',
    content,
    portalUrl: 'https://pgportal.gov.in/',
    portalName: 'CPGRAMS Portal (PM Office)',
    fee: 'Free',
  };
}
